//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Cat Folder/Script/Enemies/navmesh/tester.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Tester : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Tester()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""tester"",
    ""maps"": [
        {
            ""name"": ""navmesh"",
            ""id"": ""47980de5-9007-4fe0-8cfa-bf71b4950905"",
            ""actions"": [
                {
                    ""name"": ""testering"",
                    ""type"": ""Button"",
                    ""id"": ""d19e5d3f-9de3-45f7-b6ec-e1af2ad4e527"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e1144c2-0d07-4626-ba01-1f291d7ddf2d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""testering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // navmesh
        m_navmesh = asset.FindActionMap("navmesh", throwIfNotFound: true);
        m_navmesh_testering = m_navmesh.FindAction("testering", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // navmesh
    private readonly InputActionMap m_navmesh;
    private INavmeshActions m_NavmeshActionsCallbackInterface;
    private readonly InputAction m_navmesh_testering;
    public struct NavmeshActions
    {
        private @Tester m_Wrapper;
        public NavmeshActions(@Tester wrapper) { m_Wrapper = wrapper; }
        public InputAction @testering => m_Wrapper.m_navmesh_testering;
        public InputActionMap Get() { return m_Wrapper.m_navmesh; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavmeshActions set) { return set.Get(); }
        public void SetCallbacks(INavmeshActions instance)
        {
            if (m_Wrapper.m_NavmeshActionsCallbackInterface != null)
            {
                @testering.started -= m_Wrapper.m_NavmeshActionsCallbackInterface.OnTestering;
                @testering.performed -= m_Wrapper.m_NavmeshActionsCallbackInterface.OnTestering;
                @testering.canceled -= m_Wrapper.m_NavmeshActionsCallbackInterface.OnTestering;
            }
            m_Wrapper.m_NavmeshActionsCallbackInterface = instance;
            if (instance != null)
            {
                @testering.started += instance.OnTestering;
                @testering.performed += instance.OnTestering;
                @testering.canceled += instance.OnTestering;
            }
        }
    }
    public NavmeshActions @navmesh => new NavmeshActions(this);
    public interface INavmeshActions
    {
        void OnTestering(InputAction.CallbackContext context);
    }
}
